// Currently is just an article list, when more note types are supported, we will have to
// redesign the API
export const FETCH_SPENT_TIMELOGS_REQUEST = "FETCH_SPENT_TIMELOGS_REQUEST";
export const FETCH_SPENT_TIMELOGS_SUCCESS = "FETCH_SPENT_TIMELOGS_SUCCESS";
export const FETCH_SPENT_TIMELOGS_FAILURE = "FETCH_SPENT_TIMELOGS_FAILURE";

export const FETCH_REMAINING_TIMELOGS_REQUEST =
  "FETCH_REMAINING_TIMELOGS_REQUEST";
export const FETCH_REMAINING_TIMELOGS_SUCCESS =
  "FETCH_REMAINING_TIMELOGS_SUCCESS";
export const FETCH_REMAINING_TIMELOGS_FAILURE =
  "FETCH_REMAINING_TIMELOGS_FAILURE";

export const DELETE_TIMELOGS_REQUEST = "DELETE_TIMELOGS_REQUEST";
export const DELETE_TIMELOGS_SUCCESS = "DELETE_TIMELOGS_SUCCESS";
export const DELETE_TIMELOGS_FAILURE = "DELETE_TIMELOGS_FAILURE";

export const FETCH_SCRATCHPADS_REQUEST = "FETCH_SCRATCHPADS_REQUEST";
export const FETCH_SCRATCHPADS_SUCCESS = "FETCH_SCRATCHPADS_SUCCESS";
export const FETCH_SCRATCHPADS_FAILURE = "FETCH_SCRATCHPADS_FAILURE";

export const CREATE_SCRATCHPADS_REQUEST = "CREATE_SCRATCHPADS_REQUEST";
export const CREATE_SCRATCHPADS_SUCCESS = "CREATE_SCRATCHPADS_SUCCESS";
export const CREATE_SCRATCHPADS_FAILURE = "CREATE_SCRATCHPADS_FAILURE";

export const SET_SCRATCHPAD_REQUEST = "SET_SCRATCHPAD_REQUEST";
export const SET_SCRATCHPAD_SUCCESS = "SET_SCRATCHPAD_SUCCESS";
export const SET_SCRATCHPAD_FAILURE = "SET_SCRATCHPAD_FAILURE";
