// Currently is just an article list, when more note types are supported, we will have to
// redesign the API
export const FETCH_SPENT_TIMELOGS_REQUEST = "FETCH_SPENT_TIMELOGS_REQUEST";
export const FETCH_SPENT_TIMELOGS_SUCCESS = "FETCH_SPENT_TIMELOGS_SUCCESS";
export const FETCH_SPENT_TIMELOGS_FAILURE = "FETCH_SPENT_TIMELOGS_FAILURE";

export const FETCH_REMAINING_TIMELOGS_REQUEST =
  "FETCH_REMAINING_TIMELOGS_REQUEST";
export const FETCH_REMAINING_TIMELOGS_SUCCESS =
  "FETCH_REMAINING_TIMELOGS_SUCCESS";
export const FETCH_REMAINING_TIMELOGS_FAILURE =
  "FETCH_REMAINING_TIMELOGS_FAILURE";

export const DELETE_TIMELOGS_REQUEST = "DELETE_TIMELOGS_REQUEST";
export const DELETE_TIMELOGS_SUCCESS = "DELETE_TIMELOGS_SUCCESS";
export const DELETE_TIMELOGS_FAILURE = "DELETE_TIMELOGS_FAILURE";

export const FETCH_ALL_SCRATCHPADS_REQUEST = "FETCH_ALL_SCRATCHPADS_REQUEST";
export const FETCH_ALL_SCRATCHPADS_SUCCESS = "FETCH_ALL_SCRATCHPADS_SUCCESS";
export const FETCH_ALL_SCRATCHPADS_FAILURE = "FETCH_ALL_SCRATCHPADS_FAILURE";

export const FETCH_SCRATCHPADS_REQUEST = "FETCH_SCRATCHPADS_REQUEST";
export const FETCH_SCRATCHPADS_SUCCESS = "FETCH_SCRATCHPADS_SUCCESS";
export const FETCH_SCRATCHPADS_FAILURE = "FETCH_SCRATCHPADS_FAILURE";

export const FETCH_ARCHIVED_SCRATCHPADS_REQUEST =
  "FETCH_ARCHIVED_SCRATCHPADS_REQUEST";
export const FETCH_ARCHIVED_SCRATCHPADS_SUCCESS =
  "FETCH_ARCHIVED_SCRATCHPADS_SUCCESS";
export const FETCH_ARCHIVED_SCRATCHPADS_FAILURE =
  "FETCH_ARCHIVED_SCRATCHPADS_FAILURE";

export const CREATE_SCRATCHPADS_REQUEST = "CREATE_SCRATCHPADS_REQUEST";
export const CREATE_SCRATCHPADS_SUCCESS = "CREATE_SCRATCHPADS_SUCCESS";
export const CREATE_SCRATCHPADS_FAILURE = "CREATE_SCRATCHPADS_FAILURE";

export const CREATE_PAGE_REQUEST = "CREATE_PAGE_REQUEST";
export const CREATE_PAGE_SUCCESS = "CREATE_PAGE_SUCCESS";
export const CREATE_PAGE_FAILURE = "CREATE_PAGE_FAILURE";

export const FETCH_PAGES_REQUEST = "FETCH_PAGES_REQUEST";
export const FETCH_PAGES_SUCCESS = "FETCH_PAGES_SUCCESS";
export const FETCH_PAGES_FAILURE = "FETCH_PAGES_FAILURE";

export const SET_SCRATCHPAD_REQUEST = "SET_SCRATCHPAD_REQUEST";
export const SET_SCRATCHPAD_SUCCESS = "SET_SCRATCHPAD_SUCCESS";
export const SET_SCRATCHPAD_FAILURE = "SET_SCRATCHPAD_FAILURE";

export const ARCHIVE_SCRATCHPAD_REQUEST = "ARCHIVE_SCRATCHPAD_REQUEST";
export const ARCHIVE_SCRATCHPAD_SUCCESS = "ARCHIVE_SCRATCHPAD_SUCCESS";
export const ARCHIVE_SCRATCHPAD_FAILURE = "ARCHIVE_SCRATCHPAD_FAILURE";

export const ARCHIVE_PAGE_REQUEST = "ARCHIVE_PAGE_REQUEST";
export const ARCHIVE_PAGE_SUCCESS = "ARCHIVE_PAGE_SUCCESS";
export const ARCHIVE_PAGE_FAILURE = "ARCHIVE_PAGE_FAILURE";
