// Currently is just an article list, when more note types are supported, we will have to
// redesign the API
export const FETCH_SPRINTS_REQUEST = "FETCH_SPRINTS_REQUEST";
export const FETCH_SPRINTS_SUCCESS = "FETCH_SPRINTS_SUCCESS";
export const FETCH_SPRINTS_FAILURE = "FETCH_SPRINTS_FAILURE";

export const FETCH_SPRINT_ISSUES_REQUEST = "FETCH_SPRINT_ISSUES_REQUEST";
export const FETCH_SPRINT_ISSUES_SUCCESS = "FETCH_SPRINT_ISSUES_SUCCESS";
export const FETCH_SPRINT_ISSUES_FAILURE = "FETCH_SPRINT_ISSUES_FAILURE";
